site_name: Lectures
nav:
  - Lectures:
      - lectures/index.md
      - JavaScript Fundamentals:
          - lectures/javascript-fundamentals/index.md
          - lectures/javascript-fundamentals/history.md
          - lectures/javascript-fundamentals/tc39.md
          - lectures/javascript-fundamentals/references.md
          - lectures/javascript-fundamentals/assert.md
          - lectures/javascript-fundamentals/variables.md
          - lectures/javascript-fundamentals/values.md
          - lectures/javascript-fundamentals/primitive-values.md
          - lectures/javascript-fundamentals/complex-values.md
          - lectures/javascript-fundamentals/statements-vs-expressions.md
          - lectures/javascript-fundamentals/conditions.md
          - lectures/javascript-fundamentals/loops.md
          - lectures/javascript-fundamentals/functions.md
          - lectures/javascript-fundamentals/exceptions.md
          - lectures/javascript-fundamentals/classes.md
          - lectures/javascript-fundamentals/asynchronicity.md
      - Browser API:
          - lectures/browser-api/index.md
          - lectures/browser-api/browser-vs-node.md
          - lectures/browser-api/html.md
          - lectures/browser-api/web-apis.md
          - lectures/browser-api/dom.md
          - lectures/browser-api/element.md
          - lectures/browser-api/xmlhttprequest.md
          - lectures/browser-api/fetch.md
      - React:
          - lectures/react/index.md
      - BYOT (Build Your Own Tool):
          - lectures/byot/index.md
          - lectures/byot/installation.md
          - lectures/byot/setup.md
          - lectures/byot/content-type.md
          - lectures/byot/roles-and-permissions.md
          - lectures/byot/api.md
          - lectures/byot/setup-next.md
          - lectures/byot/client.md
          - lectures/byot/add-theme.md
          - lectures/byot/implement-the-frontend.md
theme:
  name: material
  features:
    - instant
    - tabs
markdown_extensions:
  - attr_list
  - admonition
