site_name: Lectures
site_url: http://bykof.github.com
nav:
  - Lectures:
      - lectures/index.md
      - JavaScript Fundamentals:
          - lectures/javascript-fundamentals/index.md
          - lectures/javascript-fundamentals/history.md
          - lectures/javascript-fundamentals/tc39.md
          - lectures/javascript-fundamentals/references.md
          - lectures/javascript-fundamentals/assert.md
          - lectures/javascript-fundamentals/variables.md
          - lectures/javascript-fundamentals/values.md
          - lectures/javascript-fundamentals/primitive-values.md
          - lectures/javascript-fundamentals/complex-values.md
          - lectures/javascript-fundamentals/json.md
          - lectures/javascript-fundamentals/statements-vs-expressions.md
          - lectures/javascript-fundamentals/conditions.md
          - lectures/javascript-fundamentals/loops.md
          - lectures/javascript-fundamentals/functions.md
          - lectures/javascript-fundamentals/exceptions.md
          - lectures/javascript-fundamentals/classes.md
          - lectures/javascript-fundamentals/asynchronicity.md
      - Browser API:
          - lectures/browser-api/index.md
          - lectures/browser-api/browser-vs-node.md
          - lectures/browser-api/html.md
          - lectures/browser-api/web-apis.md
          - lectures/browser-api/dom.md
          - lectures/browser-api/element.md
          - lectures/browser-api/xmlhttprequest.md
          - lectures/browser-api/fetch.md
      - React:
          - lectures/react/index.md
          - lectures/react/render-engine.md
          - lectures/react/component.md
          - lectures/react/jsx.md
          - lectures/react/reactdom-render.md
          - lectures/react/events.md
          - lectures/react/props.md
          - lectures/react/children.md
          - lectures/react/hooks.md
          - lectures/react/context.md
      - Web Workers in React:
          - lectures/web-workers-in-react/introduction.md
          - lectures/web-workers-in-react/tutorial.md
      - BYOT (Build Your Own Tool):
          - lectures/byot/index.md
          - lectures/byot/installation.md
          - lectures/byot/setup.md
          - lectures/byot/content-type.md
          - lectures/byot/roles-and-permissions.md
          - lectures/byot/api.md
          - lectures/byot/setup-next.md
          - lectures/byot/client.md
          - lectures/byot/add-theme.md
          - lectures/byot/implement-the-frontend.md
  - Exercises:
      - exercises/index.md
      - JavaScript Fundamentals:
          - exercises/javascript-fundamentals/index.md
          - exercises/javascript-fundamentals/shop/index.md
      - Browser API:
          - exercises/browser-api/shop/index.md
    # - React:
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: lime
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - attr_list
  - admonition

extra_javascript:
  - javascripts/extra.js
