site_name: Michael Bykovski Lectures
site_url: https://bykof.github.io/
nav:
    - Homepage:
          - index.md
    - React:
          - react/getting_started.md
          - react/jsx.md
          - react/setting_up.md
          - react/components.md
          - react/props.md
          - react/events.md
          - react/hooks.md
          - react/conditional_rendering.md
          - react/forms.md
          - react/component_lifecycles.md
          - react/controlled_versus_uncontrolled.md
          - react/context.md
          - react/custom_hooks.md
          - react/fetch_and_useQuery.md
          - react/react-router.md
          - react/chakra-ui.md
          - react/project_structure.md
          - react/openapi.md
    - JavaScript:
          - javascript/index.md
          - BYOT (Build Your Own Tool):
                - javascript/byot/index.md
                - javascript/byot/installation.md
                - javascript/byot/setup.md
                - javascript/byot/content-type.md
                - javascript/byot/roles-and-permissions.md
                - javascript/byot/api.md
                - javascript/byot/setup-next.md
                - javascript/byot/client.md
                - javascript/byot/add-theme.md
                - javascript/byot/implement-the-frontend.md
    - Golang:
          - golang/index.md
          - Golang Fundamentals:
                - golang/golang-fundamentals/introduction.md
                - golang/golang-fundamentals/grammar.md
                - golang/golang-fundamentals/primitive_types_and_declarations.md
                - golang/golang-fundamentals/composite_types.md
                - golang/golang-fundamentals/control_structures.md
                - golang/golang-fundamentals/functions.md
                - golang/golang-fundamentals/pointers.md
                - golang/golang-fundamentals/types_interfaces_methods.md
                - golang/golang-fundamentals/errors.md
                - golang/golang-fundamentals/modules_packages_imports.md
                - golang/golang-fundamentals/concurrency.md
                - golang/golang-fundamentals/standard_library.md
                - golang/golang-fundamentals/logging.md
                - golang/golang-fundamentals/context.md
                - golang/golang-fundamentals/tests.md
                - golang/golang-fundamentals/reflect.md
                - golang/golang-fundamentals/tags.md
                - golang/golang-fundamentals/generics.md
                - golang/golang-fundamentals/third_party_libraries.md
          - Dependency Injection:
                - golang/dependency_injection/index.md
                - golang/dependency_injection/wire.md
          - Architecture and Best Practices:
                - golang/architecture/index.md
          - Docker:
                - golang/docker/index.md
          - Design Patterns:
                - golang/design_patterns/index.md
          # - GRPC:
          #   - golang/grpc/index.md
    - Exercises:
          - exercises/index.md
          - JavaScript Fundamentals:
                - exercises/javascript-fundamentals/index.md
                - exercises/javascript-fundamentals/shop/index.md
          - Browser API:
                - exercises/browser-api/shop/index.md
          - Go:
                - exercises/go/starter/index.md
                - exercises/go/projects/school.md
                - exercises/go/projects/product_service.md
          - React:
                - exercises/react/index.md
                - exercises/react/components/index.md
                - exercises/react/hooks/index.md
                - exercises/react/forms/index.md
                - exercises/react/context/index.md
                - exercises/react/requests/index.md
                - exercises/react/routing/index.md
                - exercises/react/mantine/index.md

theme:
    name: material
    palette:
        - scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: lime
          accent: yellow
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.top
markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.highlight:
          use_pygments: true
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

extra_javascript:
    - javascripts/extra.js
